config/routes.rb
Rails.application.routes.draw do
  get '/debtors/:id', to: 'debtors#show', as: 'debtor'
  get '/debtors', to: 'debtors#index', as: 'debtors'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/debtor.rb
class Debtor < ApplicationRecord

  GENDER_TRANSLATION = {'0001' => 'Frau', '0002' => 'Herr', '0003' => 'Firma'}

  # made specific methods when to call validation for challenge. Just to demo in challenge.
  before_validation :translate_gender, on: [ :create, :save ]

  validates :system_id, :customer_number, :gender, :first_name, :last_name,
            :iso_code_language, :iso_code_language,
            :iso_code_communication_language, :iso_code_address_country,
            :zip, :city, :street, :house_number,
            :phone_number, :mobile_phone_number, :email_address, presence: true

  # add more validations in the future for data formats.
  validates :system_id, uniqueness: true
  validates :gender, inclusion: { in: ['Frau', 'Herr', 'Firma'] }

  private

  def translate_gender
    unless GENDER_TRANSLATION.values.map { |value| self.gender == value }.any?
      self.gender = GENDER_TRANSLATION[self.gender]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/debtors_controller.rb
class DebtorsController < ApplicationController
  before_action :set_debtor, only: [:show]

  def index
    @debtors = Debtor.all # just doing .all in challenge, otherwise use e.g. pagination.
  end

  def show
  end

  private

    def set_debtor
      @debtor = Debtor.find(params[:id])
    end

    def debtor_params
      params.fetch(:debtor, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/debtors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Debtors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @debtors.each do |debtor| %>
      <tr>
        <td><%= link_to 'Show', debtor_path(debtor) %></td>
        <td><%= debtor.system_id %></td>
        <td><%= debtor.customer_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/debtors/show.html.erb
<p id="notice"><%= notice %></p>

<ul>
  <% @debtor.attributes.except("id", "created_at", "updated_at")
    .each do |field, attribute| %>
    <li><strong><%= field %></strong> <%= attribute %></li>
  <% end %>
</ul>

<%= link_to 'Back', debtors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PairFinanceChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>